In [109]:
import numpy as np
import pandas as pd

In [110]:
eam_data = {'name': ['honggildong', 'kimyuna', 'parkjiwoo', 'leeseulgi'],
            'math': [90, 80, 70, 60],
            'english': [85, 95, 75, 65],
            'music': [100, 90, 80, 70],
            'physics': [95, 85, 75, 65]}

In [111]:
df = pd.DataFrame(eam_data)
df

          name  math  english  music  physics
0  honggildong    90       85    100       95
1      kimyuna    80       95     90       85
2    parkjiwoo    70       75     80       75
3    leeseulgi    60       65     70       65

In [112]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [113]:
# Changing index labels to custom values using list
df.index = ['one', 'two', 'three', 'four']

In [114]:
df.index

Index(['one', 'two', 'three', 'four'], dtype='object')

In [115]:
df

              name  math  english  music  physics
one    honggildong    90       85    100       95
two        kimyuna    80       95     90       85
three    parkjiwoo    70       75     80       75
four     leeseulgi    60       65     70       65

In [116]:
# Accessing rows using custom index labels
df.loc['three'] # Accessing row with index label 'three' which displays all columns for that row in a Series format

name       parkjiwoo
math              70
english           75
music             80
physics           75
Name: three, dtype: object

In [117]:
df.loc[['three']] # Accessing row with index label 'three' which displays all columns for that row in a DataFrame format

            name  math  english  music  physics
three  parkjiwoo    70       75     80       75

In [118]:
df['english'] # Accessing column using column name

one      85
two      95
three    75
four     65
Name: english, dtype: int64

In [119]:
df['music'] # Accessing another column using column name which displays all rows for that column in a Series format

one      100
two       90
three     80
four      70
Name: music, dtype: int64

In [120]:
df[['music', 'english']]  # Accessing multiple columns using list with column names which displays all rows for those columns in a DataFrame format

       music  english
one      100       85
two       90       95
three     80       75
four      70       65

In [121]:
#Setting the names as the index
df.set_index('name', inplace=True)

In [122]:
df  # Accessing rows using new integer index labels

             math  english  music  physics
name
honggildong    90       85    100       95
kimyuna        80       95     90       85
parkjiwoo      70       75     80       75
leeseulgi      60       65     70       65

In [123]:
df

             math  english  music  physics
name
honggildong    90       85    100       95
kimyuna        80       95     90       85
parkjiwoo      70       75     80       75
leeseulgi      60       65     70       65

In [124]:
a = df.loc['parkjiwoo', 'music'] # Accessing specific value using loc with row and column labels

In [125]:
print(a)

80

In [126]:
b = df.iloc[1, 3] # Accessing specific value using iloc with row and column positions

In [127]:
print(b)

85

In [128]:
c = df.loc['kimyuna', ['music', 'english']]  # Accessing row using loc with row label

In [129]:
print(c)

music      90
english    95
Name: kimyuna, dtype: int64

In [130]:
df.loc['leeseulgi', ['math', 'english']] = 90,95 # Updating specific values using loc with row label and column labels

In [131]:
df

             math  english  music  physics
name
honggildong    90       85    100       95
kimyuna        80       95     90       85
parkjiwoo      70       75     80       75
leeseulgi      90       95     70       65

In [132]:
df.mean()

math       82.5
english    87.5
music      85.0
physics    80.0
dtype: float64

In [133]:
# df.avg()  # This will raise an AttributeError since 'DataFrame' object has no attribute 'avg'
df.median()  # This will work correctly and return the median of each column

math       85.0
english    90.0
music      85.0
physics    80.0
dtype: float64

In [134]:
d =df.iloc[0, [1, 2]] # Accessing specific values using iloc with row position and list of column positions

In [135]:
print(d)

english     85
music      100
Name: honggildong, dtype: int64

In [152]:
d =df.iloc[3, [0, 3]] # Accessing specific values using iloc with row position and list of column positions

In [153]:
print(d)

math       90
physics    65
Name: leeseulgi, dtype: int64

In [154]:
df.iloc[1:3, 1:3] # Accessing a subset of the DataFrame using iloc with row and column position ranges

           english  music
name
kimyuna         95     90
parkjiwoo       75     80

In [155]:
df.iloc[1, 1:3] # Accessing a subset of the DataFrame using iloc with row position and column position ranges

english    95
music      90
Name: kimyuna, dtype: int64

In [156]:
df.loc['kimyuna' : 'leeseulgi', 'math' :  'music']  # Accessing multiple rows and columns using loc with row and column labels

           math  english  music
name
kimyuna      80       95     90
parkjiwoo    70       75     80
leeseulgi    90       95     70

In [157]:
df['Chemistry'] = [100, 90, 80, 70]  # Adding a new column to the DataFrame

In [158]:
df

             math  english  music  physics  Chemistry
name
honggildong    90       85    100       95        100
kimyuna        80       95     90       85         90
parkjiwoo      70       75     80       75         80
leeseulgi      90       95     70       65         70

In [159]:
df.reindex

<bound method DataFrame.reindex of              math  english  music  physics  Chemistry
name
honggildong    90       85    100       95        100
kimyuna        80       95     90       85         90
parkjiwoo      70       75     80       75         80
leeseulgi      90       95     70       65         70>

In [160]:
df

             math  english  music  physics  Chemistry
name
honggildong    90       85    100       95        100
kimyuna        80       95     90       85         90
parkjiwoo      70       75     80       75         80
leeseulgi      90       95     70       65         70

In [161]:
df.reset_index()

          name  math  english  music  physics  Chemistry
0  honggildong    90       85    100       95        100
1      kimyuna    80       95     90       85         90
2    parkjiwoo    70       75     80       75         80
3    leeseulgi    90       95     70       65         70

In [162]:
df.iloc[1:3, 1:3] # Accessing a subset of the DataFrame using iloc with row and column position ranges

           english  music
name
kimyuna         95     90
parkjiwoo       75     80

In [163]:
df.iloc[3]

math         90
english      95
music        70
physics      65
Chemistry    70
Name: leeseulgi, dtype: int64

In [166]:
# df.loc[4] = ['johndoe', 88, 77, 66, 55, 99]  # Adding a new row to the DataFrame using loc with a new index label
df.loc[4] = 0

In [167]:
df

             math  english  music  physics  Chemistry
name
honggildong    90       85    100       95        100
kimyuna        80       95     90       85         90
parkjiwoo      70       75     80       75         80
leeseulgi      90       95     70       65         70
4               0        0      0        0          0

In [169]:
df.loc[4] = [88, 77, 66, 55, 99]  # Adding a new row using loc with a new index label

In [170]:
df

             math  english  music  physics  Chemistry
name
honggildong    90       85    100       95        100
kimyuna        80       95     90       85         90
parkjiwoo      70       75     80       75         80
leeseulgi      90       95     70       65         70
4              88       77     66       55         99

In [ ]:
df.iloc[]