In [3]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
df = pd.read_csv('data_studentlist.csv')

In [5]:
df.head(10) # first 10 rows

               Name Gender  Age  Grade Absence Bloodtype  Height  Weight
0     Jared Diamond      M   23      3       Y         O   165.3    68.2
1    Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2      Brian Martin      M   24      4       N         B   175.0    80.1
3      David Hassel      M   23      3       N        AB   182.1    85.7
4   Clara Rodriquez      F   20      1       Y         A   168.0    49.5
5  Jennifer Lorentz      F   21      2       N         O   162.0    52.0
6       Susan Clark      F   22      1       N         O   155.2    45.3
7   Margareth Jones      F   23      1       N         A   176.9    55.0
8      John Bertsch      M   23      3       N         B   178.5    64.2
9    Jake Timmerman      M   22      2       N         B   176.1    61.3

In [6]:
df.tail(10) # last 10 rows

                Name Gender  Age  Grade Absence Bloodtype  Height  Weight
7    Margareth Jones      F   23      1       N         A   176.9    55.0
8       John Bertsch      M   23      3       N         B   178.5    64.2
9     Jake Timmerman      M   22      2       N         B   176.1    61.3
10     Joshua Connor      M   24      4       Y         O   167.1    62.0
11      John Matsuda      M   22      2       N        AB   180.0    75.8
12      Eddy Johnson      M   21      1       N         A   162.2    55.3
13  Rebecah Anderson      F   23      3       N         O   176.1    53.1
14      Linda Carter      F   22      2       N         B   158.2    45.2
15    Richard Swayze      M   24      4       Y         B   168.6    70.2
16       Andrew King      M   21      1       N         A   169.2    62.2

In [7]:
df

                Name Gender  Age  Grade Absence Bloodtype  Height  Weight
0      Jared Diamond      M   23      3       Y         O   165.3    68.2
1     Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2       Brian Martin      M   24      4       N         B   175.0    80.1
3       David Hassel      M   23      3       N        AB   182.1    85.7
4    Clara Rodriquez      F   20      1       Y         A   168.0    49.5
5   Jennifer Lorentz      F   21      2       N         O   162.0    52.0
6        Susan Clark      F   22      1       N         O   155.2    45.3
7    Margareth Jones      F   23      1       N         A   176.9    55.0
8       John Bertsch      M   23      3       N         B   178.5    64.2
9     Jake Timmerman      M   22      2       N         B   176.1    61.3
10     Joshua Connor      M   24      4       Y         O   167.1    62.0
11      John Matsuda      M   22      2       N        AB   180.0    75.8
12      Eddy Johnson      M   21      1       N         A   162.2    55.3
13  Rebecah Anderson      F   23      3       N         O   176.1    53.1
14      Linda Carter      F   22      2       N         B   158.2    45.2
15    Richard Swayze      M   24      4       Y         B   168.6    70.2
16       Andrew King      M   21      1       N         A   169.2    62.2

In [8]:
df['Gender'].value_counts() # count of unique values in a column

Gender
M    10
F     7
Name: count, dtype: int64

In [9]:
df['Age'].mean() # mean of a column

np.float64(22.352941176470587)

In [10]:
df['Age'].max() # max of a column

np.int64(24)

In [11]:
df.groupby(['Gender', 'Grade'])['Age'].mean()

Gender  Grade
F       1        21.666667
        2        21.666667
        3        23.000000
M       1        21.000000
        2        22.000000
        3        23.000000
        4        24.000000
Name: Age, dtype: float64

In [12]:
df.groupby(['Bloodtype'])['Height'].mean()

Bloodtype
A     169.075
AB    177.400
B     171.280
O     165.140
Name: Height, dtype: float64