In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.read_csv('iris.csv')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
# data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [5]:
iris = pd.read_csv('iris.csv')

In [6]:
#Display first 5 rows
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
#Display last 5 rows
iris.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [8]:
type(iris)

pandas.core.frame.DataFrame

In [9]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [10]:
print(iris.SepalLengthCm)
print(iris.PetalLengthCm)
print(iris.PetalWidthCm)
print(iris.SepalWidthCm)
print(iris.Species)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64
0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: PetalLengthCm, Length: 150, dtype: float64
0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: PetalWidthCm, Length: 150, dtype: float64
0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: SepalWidthCm, Length: 150, dtype: float64
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [11]:
#Summary of the dataframe
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [12]:
iris["SepalLengthCm"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [13]:
#Count of unique values in Species column along with their frequency of occurrence
iris["PetalLengthCm"].value_counts()

PetalLengthCm
1.5    14
1.4    12
4.5     8
5.1     8
1.3     7
1.6     7
5.6     6
4.9     5
4.0     5
4.7     5
1.7     4
4.8     4
5.0     4
4.4     4
4.2     4
4.1     3
3.9     3
5.8     3
5.7     3
5.5     3
6.1     3
4.6     3
1.9     2
5.2     2
5.4     2
1.2     2
3.3     2
3.5     2
6.7     2
5.3     2
4.3     2
5.9     2
6.0     2
1.0     1
1.1     1
3.7     1
3.8     1
3.6     1
3.0     1
6.3     1
6.6     1
6.9     1
6.4     1
Name: count, dtype: int64

In [14]:
#Displays the information about the Iris-virginica species
iris[iris["Species"] == "Iris-virginica"]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [15]:
#Count of unique rows for Iris-virginica species along with their frequency of occurrence
iris[iris["Species"] == "Iris-virginica"].value_counts()

Id   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
101  6.3            3.3           6.0            2.5           Iris-virginica    1
102  5.8            2.7           5.1            1.9           Iris-virginica    1
103  7.1            3.0           5.9            2.1           Iris-virginica    1
104  6.3            2.9           5.6            1.8           Iris-virginica    1
105  6.5            3.0           5.8            2.2           Iris-virginica    1
106  7.6            3.0           6.6            2.1           Iris-virginica    1
107  4.9            2.5           4.5            1.7           Iris-virginica    1
108  7.3            2.9           6.3            1.8           Iris-virginica    1
109  6.7            2.5           5.8            1.8           Iris-virginica    1
110  7.2            3.6           6.1            2.5           Iris-virginica    1
111  6.5            3.2           5.1            2.0           Iris-virginica    1
112  6.4            2.7           5.3            1.9           Iris-virginica    1
113  6.8            3.0           5.5            2.1           Iris-virginica    1
114  5.7            2.5           5.0            2.0           Iris-virginica    1
115  5.8            2.8           5.1            2.4           Iris-virginica    1
116  6.4            3.2           5.3            2.3           Iris-virginica    1
117  6.5            3.0           5.5            1.8           Iris-virginica    1
118  7.7            3.8           6.7            2.2           Iris-virginica    1
119  7.7            2.6           6.9            2.3           Iris-virginica    1
120  6.0            2.2           5.0            1.5           Iris-virginica    1
121  6.9            3.2           5.7            2.3           Iris-virginica    1
122  5.6            2.8           4.9            2.0           Iris-virginica    1
123  7.7            2.8           6.7            2.0           Iris-virginica    1
124  6.3            2.7           4.9            1.8           Iris-virginica    1
125  6.7            3.3           5.7            2.1           Iris-virginica    1
126  7.2            3.2           6.0            1.8           Iris-virginica    1
127  6.2            2.8           4.8            1.8           Iris-virginica    1
128  6.1            3.0           4.9            1.8           Iris-virginica    1
129  6.4            2.8           5.6            2.1           Iris-virginica    1
130  7.2            3.0           5.8            1.6           Iris-virginica    1
131  7.4            2.8           6.1            1.9           Iris-virginica    1
132  7.9            3.8           6.4            2.0           Iris-virginica    1
133  6.4            2.8           5.6            2.2           Iris-virginica    1
134  6.3            2.8           5.1            1.5           Iris-virginica    1
135  6.1            2.6           5.6            1.4           Iris-virginica    1
136  7.7            3.0           6.1            2.3           Iris-virginica    1
137  6.3            3.4           5.6            2.4           Iris-virginica    1
138  6.4            3.1           5.5            1.8           Iris-virginica    1
139  6.0            3.0           4.8            1.8           Iris-virginica    1
140  6.9            3.1           5.4            2.1           Iris-virginica    1
141  6.7            3.1           5.6            2.4           Iris-virginica    1
142  6.9            3.1           5.1            2.3           Iris-virginica    1
143  5.8            2.7           5.1            1.9           Iris-virginica    1
144  6.8            3.2           5.9            2.3           Iris-virginica    1
145  6.7            3.3           5.7            2.5           Iris-virginica    1
146  6.7            3.0           5.2            2.3           Iris-virginica    1
147  6.3            2.5           5.0            1.9           Iris-virginica    1
148  6.5            3.0           5.2            2.0           Iris-virginica    1
149  6.2            3.4           5.4            2.3           Iris-virginica    1
150  5.9            3.0           5.1            1.8           Iris-virginica    1
Name: count, dtype: int64

In [16]:
iris["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [17]:
iris.index

RangeIndex(start=0, stop=150, step=1)

In [18]:
iris.SepalWidthCm

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: SepalWidthCm, Length: 150, dtype: float64

In [19]:
#Create a dataframe from dictionary
data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18],
        'Gender': ['M', 'M', 'M', 'M'],
        'Marks': [85.5, 90.5, 78.0, 92.0],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}

In [20]:
#Displays as a Dictionary
data

{'Name': ['Tom', 'nick', 'krish', 'jack'],
 'Age': [20, 21, 19, 18],
 'Gender': ['M', 'M', 'M', 'M'],
 'Marks': [85.5, 90.5, 78.0, 92.0],
 'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']}

In [21]:
type(data)

dict

In [22]:
#Display as DataFrame
data_df = pd.DataFrame(data)
data_df

    Name  Age Gender  Marks         City
0    Tom   20      M   85.5     New York
1   nick   21      M   90.5  Los Angeles
2  krish   19      M   78.0      Chicago
3   jack   18      M   92.0      Houston

In [23]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Gender  4 non-null      object
 3   Marks   4 non-null      float64
 4   City    4 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 292.0+ bytes

In [24]:
data_df.head()

    Name  Age Gender  Marks         City
0    Tom   20      M   85.5     New York
1   nick   21      M   90.5  Los Angeles
2  krish   19      M   78.0      Chicago
3   jack   18      M   92.0      Houston

In [25]:
data_df.columns

Index(['Name', 'Age', 'Gender', 'Marks', 'City'], dtype='object')

In [26]:
#Summary statistics of DataFrame
data_df.describe()

             Age      Marks
count   4.000000   4.000000
mean   19.500000  86.500000
std     1.290994   6.311365
min    18.000000  78.000000
25%    18.750000  83.625000
50%    19.500000  88.000000
75%    20.250000  90.875000
max    21.000000  92.000000

In [27]:
%pip install seaborn

Requirement already satisfied: seaborn in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: pandas>=1.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [28]:
import seaborn as sns

In [29]:
df = sns.load_dataset('titanic')

In [30]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [31]:
nan_deck_1 = df['deck'].value_counts(dropna = False) #Not a Number deck(nan_deck)

In [32]:
print(nan_deck_1)
nan_deck_1

deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64

deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64

In [33]:
nan_deck_2 = df['deck'].value_counts(dropna = True) #Not a Number deck(nan_deck)

In [34]:
nan_deck_2

deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

In [35]:
df.head().notnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True

In [36]:
df.head().isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False