In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
A = pd.DataFrame({'Name' : ['Shashank', 'Rohit', 'Ankit', 'Sagar','Vivek'],
                  'Age' : [21, 22, 21, 23, 22],
                  'Gender' : ['Male', 'Male', 'Male', 'Male', 'Male']})

In [5]:
A

       Name  Age Gender
0  Shashank   21   Male
1     Rohit   22   Male
2     Ankit   21   Male
3     Sagar   23   Male
4     Vivek   22   Male

In [8]:
B = pd.DataFrame({'Name': ['Shashank', 'Ankita','Rohit'],
                  'Position': ['Data Scientist', 'Developer', 'Manager'],
                  'Salary': [100000, 80000, 120000]})

In [9]:
B

       Name        Position  Salary
0  Shashank  Data Scientist  100000
1    Ankita       Developer   80000
2     Rohit         Manager  120000

In [11]:
#Simple Merging DataFrames on Name column for common values 
pd.merge(A, B, on='Name')

       Name  Age Gender        Position  Salary
0  Shashank   21   Male  Data Scientist  100000
1     Rohit   22   Male         Manager  120000

In [12]:
pd.merge(A, B, how='left', on='Name')

       Name  Age Gender        Position    Salary
0  Shashank   21   Male  Data Scientist  100000.0
1     Rohit   22   Male         Manager  120000.0
2     Ankit   21   Male             NaN       NaN
3     Sagar   23   Male             NaN       NaN
4     Vivek   22   Male             NaN       NaN

In [13]:
pd.merge(A, B, how='right', on='Name')

       Name   Age Gender        Position  Salary
0  Shashank  21.0   Male  Data Scientist  100000
1    Ankita   NaN    NaN       Developer   80000
2     Rohit  22.0   Male         Manager  120000

In [14]:
pd.merge(A,B,on='Name', how='outer')

       Name   Age Gender        Position    Salary
0     Ankit  21.0   Male             NaN       NaN
1    Ankita   NaN    NaN       Developer   80000.0
2     Rohit  22.0   Male         Manager  120000.0
3     Sagar  23.0   Male             NaN       NaN
4  Shashank  21.0   Male  Data Scientist  100000.0
5     Vivek  22.0   Male             NaN       NaN

In [16]:
pd.merge(A,B, on = 'Name', how='inner')

       Name  Age Gender        Position  Salary
0  Shashank   21   Male  Data Scientist  100000
1     Rohit   22   Male         Manager  120000

In [23]:
%pip install openpyxl
StockPrices = pd.read_excel('./7-India-Stock-Market-Tracker_V_1_1.xlsx')

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

In [25]:
StockPrices

,Unnamed: 0,Unnamed: 1,Unnamed: 2,STOCK MARKET,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,2022-01-24 04:38:19,Unnamed: 14,Unnamed: 15,Unnamed: 16,-7,Offset
0,NaN,NaN,NaN,NaN,NIFTY 50,-468.05,-468.05 (-2.66%),NaN,NaN,NaN,NaN,SENSEX,-1545.67,-1545.67 (-2.62%),NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,17149.1,NaN,NaN,NaN,NaN,NaN,NaN,57491.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1648,NaN,1,68,NaN,-1,1570,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Stocks tracked,NaN,NaN,Gainers,NaN,NaN,Decliners,NaN,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,TOP GAINERS,NaN,NaN,NaN,NaN,TOP DECLINERS,NaN,NaN,NaN,NaN,TOP ACTIVES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,Price,Change,Change %,NaN,NaN,Price,Change,Change %,NaN,NaN,Price,Volume,Price Ch %,NaN,NaN,NaN,NaN
11,1.0,SHARDACROP,437.8,58.5,0.154231,NaN,ELECTHERM,132.9,-24.45,-0.155386,NaN,IDEA,10.95,345228541,-0.075949,NaN,NaN,NaN,NaN
12,2.0,GLOBAL,80.15,7.25,0.099451,NaN,TCI,687.65,-99.05,-0.125906,NaN,YESBANK,13.45,200908635,-0.021818,NaN,NaN,NaN,NaN
13,3.0,BANARBEADS,99.85,7.9,0.085916,NaN,ORBTEXP,88.15,-12.65,-0.125496,NaN,JPPOWER,8.8,184605790,-0.083333,NaN,NaN,NaN,NaN
14,4.0,JIKIND,1,0.05,0.052632,NaN,MMP,157.3,-22.55,-0.125382,NaN,SUZLON,11.1,76853899,-0.04721,NaN,NaN,NaN,NaN
15,5.0,JINDWORLD,327.75,15.7,0.050312,NaN,NIITLTD,406.3,-54.55,-0.118368,NaN,GTLINFRA,2.1,63935369,-0.045455,NaN,NaN,NaN,NaN
16,6.0,INDIANCARD,307.85,14.65,0.049966,NaN,JHS,26.2,-3.5,-0.117845,NaN,VIKASECO,5.8,61287588,0.045045,NaN,NaN,NaN,NaN
17,7.0,SEJALLTD,52.55,2.5,0.04995,NaN,SALONA,272.5,-35.2,-0.114397,NaN,BANKBARODA,92.6,56181631,-0.001079,NaN,NaN,NaN,NaN
18,8.0,BIGBLOC,71.5,3.4,0.049927,NaN,RAMKY,216.4,-27.9,-0.114204,NaN,SAIL,97.35,51823192,-0.050707,NaN,NaN,NaN,NaN
19,9.0,SELMC,91.8,4.35,0.049743,NaN,PNBGILTS,63.45,-8.1,-0.113208,NaN,PNB,38,51367085,-0.020619,NaN,NaN,NaN,NaN
20,10.0,GODHA,67.7,3.2,0.049612,NaN,ANGELONE,1345.35,-168.15,-0.1111,NaN,ALOKINDS,28.9,47277021,-0.083994,NaN,NaN,NaN,NaN
21,NaN,View more,NaN,NaN,NaN,NaN,View more,NaN,NaN,NaN,NaN,View more,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
StockPrices.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,STOCK MARKET,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,2022-01-24 04:38:19,Unnamed: 14,Unnamed: 15,Unnamed: 16,-7,Offset
0,NaN,NaN,NaN,NaN,NIFTY 50,-468.05,-468.05 (-2.66%),NaN,NaN,NaN,NaN,SENSEX,-1545.67,-1545.67 (-2.62%),NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,17149.1,NaN,NaN,NaN,NaN,NaN,NaN,57491.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1648,NaN,1,68,NaN,-1,1570,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN