In [1]:
import numpy as np
import pandas as pd

In [10]:
student1 = pd.Series({'Korean': 90, 'Maths': 80, 'Science': 85})

In [11]:
student1

Korean     90
Maths      80
Science    85
dtype: int64

In [12]:
Percentage = (student1 / 100) * 100 #Percentage of each subject marks

In [13]:
Percentage

Korean     90.0
Maths      80.0
Science    85.0
dtype: float64

In [14]:
Total_percentage = (student1.sum()/ 300)*100 #Total Percentage
Total_percentage

np.float64(85.0)

In [16]:
add = student1 + 5
add

Korean     95
Maths      85
Science    90
dtype: int64

In [17]:
sub = student1 - 10
sub

Korean     80
Maths      70
Science    75
dtype: int64

In [19]:
div = student1 / 10
div

Korean     9.0
Maths      8.0
Science    8.5
dtype: float64

In [21]:
#Creating new data set from the operations on the existing data set
df_1 = pd.DataFrame(data = [add, sub, div], index = ['Addition', 'Subtraction', 'Division'])
df_1

             Korean  Maths  Science
Addition       95.0   85.0     90.0
Subtraction    80.0   70.0     75.0
Division        9.0    8.0      8.5

In [24]:
student2 = pd.Series({'Korean': 80, 'Maths': 75, 'Pysics': 90})
student2

Korean    80
Maths     75
Pysics    90
dtype: int64

In [25]:
mul = student1 * student2
mul

Korean     7200.0
Maths      6000.0
Pysics        NaN
Science       NaN
dtype: float64

In [28]:
df_2 = pd.DataFrame(data = [add, sub, div, mul], index = ['Addition', 'Subtraction', 'Division', 'Multiplication'])
df_2

                Korean   Maths  Science  Pysics
Addition          95.0    85.0     90.0     NaN
Subtraction       80.0    70.0     75.0     NaN
Division           9.0     8.0      8.5     NaN
Multiplication  7200.0  6000.0      NaN     NaN

In [29]:
#Transpose of the dataframe
df_3 = df_1.T
df_3

         Addition  Subtraction  Division
Korean       95.0         80.0       9.0
Maths        85.0         70.0       8.0
Science      90.0         75.0       8.5

In [30]:
df_4 = df_2.T
df_4

         Addition  Subtraction  Division  Multiplication
Korean       95.0         80.0       9.0          7200.0
Maths        85.0         70.0       8.0          6000.0
Science      90.0         75.0       8.5             NaN
Pysics        NaN          NaN       NaN             NaN

In [4]:
%pip install seaborn

Requirement already satisfied: seaborn in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: pandas>=1.2 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import seaborn as sns

In [7]:
titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
df = titanic['survived']

In [10]:
df

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [11]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: survived
Non-Null Count  Dtype
--------------  -----
891 non-null    int64
dtypes: int64(1)
memory usage: 7.1 KB

In [18]:
df =  titanic.loc[:,[ 'age', 'fare','pclass']]
df

      age     fare  pclass
0    22.0   7.2500       3
1    38.0  71.2833       1
2    26.0   7.9250       3
3    35.0  53.1000       1
4    35.0   8.0500       3
..    ...      ...     ...
886  27.0  13.0000       2
887  19.0  30.0000       1
888   NaN  23.4500       3
889  26.0  30.0000       1
890  32.0   7.7500       3

[891 rows x 3 columns]

In [19]:
df.head()

    age     fare  pclass
0  22.0   7.2500       3
1  38.0  71.2833       1
2  26.0   7.9250       3
3  35.0  53.1000       1
4  35.0   8.0500       3

In [21]:
df_add = df + 10
df_add.head()

    age     fare  pclass
0  32.0  17.2500      13
1  48.0  81.2833      11
2  36.0  17.9250      13
3  45.0  63.1000      11
4  45.0  18.0500      13

In [23]:
df_sub = df_add - 5
df_sub.head()

    age     fare  pclass
0  27.0  12.2500       8
1  43.0  76.2833       6
2  31.0  12.9250       8
3  40.0  58.1000       6
4  40.0  13.0500       8

In [24]:
type(titanic)

pandas.core.frame.DataFrame

In [26]:
df.tail()

      age   fare  pclass
886  27.0  13.00       2
887  19.0  30.00       1
888   NaN  23.45       3
889  26.0  30.00       1
890  32.0   7.75       3

In [ ]:
df_add.tail()

      age   fare  pclass
886  37.0  23.00      12
887  29.0  40.00      11
888   NaN  33.45      13
889  36.0  40.00      11
890  42.0  17.75      13