In [3]:
import pandas as pd
import numpy as np

In [4]:
student_data = pd.DataFrame([['Name', 'Age','Gender','Course','City'],['Shashank',21,'M','B.Tech','Bangalore'],['Ravi',22,'M','B.Tech','Chennai'],['Anjali',20,'F','B.Sc','Mumbai'],['Sneha',21,'F','B.Com','Delhi']])

In [5]:
student_data

          0    1       2       3          4
0      Name  Age  Gender  Course       City
1  Shashank   21       M  B.Tech  Bangalore
2      Ravi   22       M  B.Tech    Chennai
3    Anjali   20       F    B.Sc     Mumbai
4     Sneha   21       F   B.Com      Delhi

In [6]:
student_data = pd.DataFrame([['Shashank',21,'M','B.Tech','Bangalore'],['Ravi',22,'M','B.Tech','Chennai'],['Anjali',20,'F','B.Sc','Mumbai'],['Sneha',21,'F','B.Com','Delhi']], columns=['Name','Age','Gender','Course','City'])
#Updating Column Names from default to custom values

In [7]:
student_data

       Name  Age Gender  Course       City
0  Shashank   21      M  B.Tech  Bangalore
1      Ravi   22      M  B.Tech    Chennai
2    Anjali   20      F    B.Sc     Mumbai
3     Sneha   21      F   B.Com      Delhi

In [8]:
student_data.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
#Updating Index with custom values
student_data.index = ['Stud1','Stud2','Stud3','Stud4']

In [10]:
student_data

           Name  Age Gender  Course       City
Stud1  Shashank   21      M  B.Tech  Bangalore
Stud2      Ravi   22      M  B.Tech    Chennai
Stud3    Anjali   20      F    B.Sc     Mumbai
Stud4     Sneha   21      F   B.Com      Delhi

In [11]:
student_data.index

Index(['Stud1', 'Stud2', 'Stud3', 'Stud4'], dtype='object')

In [12]:
#Renaming columns
student_data.columns = ['Student_Name','Student_Age','Student_Gender','Student_Course','Student_City']

In [13]:
student_data

      Student_Name  Student_Age Student_Gender Student_Course Student_City
Stud1     Shashank           21              M         B.Tech    Bangalore
Stud2         Ravi           22              M         B.Tech      Chennai
Stud3       Anjali           20              F           B.Sc       Mumbai
Stud4        Sneha           21              F          B.Com        Delhi

In [14]:
student_data.rename(columns={'Student_Name':'Name','Student_Age':'Age'}, inplace=True)

In [15]:
student_data

           Name  Age Student_Gender Student_Course Student_City
Stud1  Shashank   21              M         B.Tech    Bangalore
Stud2      Ravi   22              M         B.Tech      Chennai
Stud3    Anjali   20              F           B.Sc       Mumbai
Stud4     Sneha   21              F          B.Com        Delhi

In [16]:
#Drop a column just once
student_data.drop('Stud1')

         Name  Age Student_Gender Student_Course Student_City
Stud2    Ravi   22              M         B.Tech      Chennai
Stud3  Anjali   20              F           B.Sc       Mumbai
Stud4   Sneha   21              F          B.Com        Delhi

In [17]:
student_data

           Name  Age Student_Gender Student_Course Student_City
Stud1  Shashank   21              M         B.Tech    Bangalore
Stud2      Ravi   22              M         B.Tech      Chennai
Stud3    Anjali   20              F           B.Sc       Mumbai
Stud4     Sneha   21              F          B.Com        Delhi

In [18]:
#Drop a column permanently
student_data.drop('Stud3', inplace=True)

In [19]:
student_data

           Name  Age Student_Gender Student_Course Student_City
Stud1  Shashank   21              M         B.Tech    Bangalore
Stud2      Ravi   22              M         B.Tech      Chennai
Stud4     Sneha   21              F          B.Com        Delhi

In [20]:
student_data1 = student_data[:]

In [21]:
student_data1

           Name  Age Student_Gender Student_Course Student_City
Stud1  Shashank   21              M         B.Tech    Bangalore
Stud2      Ravi   22              M         B.Tech      Chennai
Stud4     Sneha   21              F          B.Com        Delhi

In [22]:
student_data2 = student_data[1:]

In [23]:
student_data2

        Name  Age Student_Gender Student_Course Student_City
Stud2   Ravi   22              M         B.Tech      Chennai
Stud4  Sneha   21              F          B.Com        Delhi

In [24]:
student_data3 = student_data[:1]

In [25]:
student_data3

           Name  Age Student_Gender Student_Course Student_City
Stud1  Shashank   21              M         B.Tech    Bangalore